### ISSUE TITLE
_api-check.shade does not handle spaces in repository path

### ISSUE THREAD

**Issue by dougbu** [aspnet/KoreBuild#137]
1. Check out an ASP.NET Core repo into a directory containing a space e.g. `git clone https://github.com/aspnet/Mvc.git 'MVC 2'`
2. Build e.g. `.\build.cmd --quiet verify`

##### Expected
Successful build

##### Observed
Build exits after failing when executing `Microsoft.AspNetCore.BuildTools.ApiCheck.exe`:
```
info: Run target: run-api-check
info: Exec
info:   program: C:\dd\dnx\MVC 2\.build\Microsoft.AspNetCore.BuildTools.ApiCheck\1.0.1-rc2-15129\tools\net451\Microsoft.AspNetCore.BuildTools.ApiCheck.exe
info:   commandline: compare -b C:\dd\dnx\MVC 2\src\Microsoft.AspNetCore.Mvc\baseline.net45.json -a C:\dd\dnx\MVC 2\src\Microsoft.AspNetCore.Mvc\bin\Debug\net451\Microsoft.AspNetCore.Mvc.dll -p C:\dd\dnx\MVC 2\src\Microsoft.AspNetCore.Mvc\project.json -c Debug -epi
info:   workingdir: C:\dd\dnx\MVC 2
Specify --help for a list of available options and commands.

Unhandled Exception: Microsoft.Extensions.CommandLineUtils.CommandParsingException: Unrecognized command or argument '2\src\Microsoft.AspNetCore.Mvc\baseline.net45.json'
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.HandleUnexpectedArg(CommandLineApplication command, String[] args, Int32 index, String argTypeName)
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at ApiCheck.Program.Main(String[] args) in C:\BuildAgent\work\94c9336e5146215d\src\Microsoft.AspNetCore.BuildTools.ApiCheck\Program.cs:line 64
fail: Exit code -532462766 from C:\dd\dnx\MVC 2\.build\Microsoft.AspNetCore.BuildTools.ApiCheck\1.0.1-rc2-15129\tools\net451\Microsoft.AspNetCore.BuildTools.ApiCheck.exe
```

**Comment by natemcmaster** [comment]
We're removing sake https://github.com/aspnet/KoreBuild/pull/195. Closing as wont-fix.
